name: flutter_avif
description: Avif support for Flutter.
version: 1.1.0
repository: https://github.com/yekeskin/flutter_avif

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_avif_platform_interface: ^1.1.0
  flutter_avif_android: ^1.1.0
  flutter_avif_ios: ^1.1.0
  flutter_avif_macos: ^1.1.0
  flutter_avif_linux: ^1.1.0
  flutter_avif_windows: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_avif_android
      ios:
        default_package: flutter_avif_ios
      macos:
        default_package: flutter_avif_macos
      linux:
        default_package: flutter_avif_linux
      windows:
        default_package: flutter_avif_windows
